# Generated by Django 4.1.2 on 2022-10-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seputaruntirta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dosen',
            name='fakultas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seputaruntirta.kelompok'),
        ),
    ]
